# -----------------------------------------------
# CONFIGURATION FOR CROP DISEASE RISK MODEL
# -----------------------------------------------

data:
  # ✨ CHANGE: Pointing to the disease-specific dataset
  csv_path: "data/crop_disease_training.csv"
  
  # The available spectral bands from Sentinel-2
  bands:
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B11
    - B12

  # ✨ CHANGE: Adjusted for a typical disease monitoring period (late summer in Lesotho)
  date_range:
    start: "2025-06-01"
    end:   "2025-08-15"

# Google Earth Engine parameters
gee:
  collection: "COPERNICUS/S2_SR_HARMONIZED"
  cloud_threshold: 20
  buffer_radius: 30

# Definitions for vegetation indices to be calculated as features.
# These are excellent for detecting plant health and stress.
indices:
  - name: NDVI
    expression: "(B8 - B4) / (B8 + B4)"
  - name: SAVI
    expression: "((B8 - B4) / (B8 + B4 + 0.5)) * 1.5"
  - name: EVI
    expression: "2.5 * ((B8 - B4) / (B8 + 6 * B4 - 7.5 * B2 + 1))"
  - name: NDRE
    expression: "(B8 - B5) / (B8 + B5)"
  - name: MSI
    expression: "B11 / B8"
  - name: OSAVI
    expression: "(B8 - B4) / (B8 + B4 + 0.16) * 1.16"
  - name: GNDVI
    expression: "(B8 - B3) / (B8 + B3)"
  - name: NDWI
    expression: "(B3 - B8) / (B3 + B8)"
  - name: RVI
    expression: "B8 / B4"
  - name: NDREI 
    expression: "(B7 - B5) / (B7 + B5)"
  - name: NDPI 
    expression: "(B8 - B6) / (B8 + B6)"
  - name: CI_RE
    expression: "(B7 / B5) - 1"
  - name: WBI
    expression: "(B9 / B12)"
  - name: Ratio_B8_B5
    expression: "B8 / B5"

# Model output files
model:
  # ✨ CHANGE: New name for the saved disease model
  name: "disease_risk_model.pkl"
  # ✨ CHANGE: New name for the corresponding features list
  features_file: "disease_risk_features.json"

# Training and validation parameters
training:
  test_size: 0.2
  random_state: 42
  cv_folds: 5

# Hyperparameter grid for GridSearchCV
grid_search:
  n_estimators: [50, 100, 200, 500]
  max_depth: [null, 5, 10, 20]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  scoring: "balanced_accuracy"